AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'

Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  CountComments: false
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false

