AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'spec/fixtures/**/*'

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  CountComments: false
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false

